name: Quality Checks
run-name: ${{ github.workflow }} of ${{ github.sha }} on ${{ github.ref_name }}

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: "${{ github.workflow }} at ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: sonarcloud
        name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - id: shellcheck
        name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  setup-and-test:
    name: Setup workstation and test
    strategy:
      fail-fast: true
      matrix:
        os: [macos-13, macos-14, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v4
      - id: setup
        name: Setup workstation
        run: ./setup
      - id: test
        name: Test setup
        run: ./test
